Pr 101 restore test (#131)
* New Sketch Throttle Controller and Inner Grip

* Update Makefile

* Update 4A9A1-THROTTLE_CONTROLLER.ino

* Update 4A9A1-THROTTLE_CONTROLLER.ino

* Update 4A9A1A1-THROTTLE_INNER_GRIP.ino

* Update 4A9A1A1-THROTTLE_INNER_GRIP.ino

* Update 4A9A1A1-THROTTLE_INNER_GRIP.ino

* refactored based on feed back, and worked through the mapped values limitations.

* Update 4A9A1-THROTTLE_CONTROLLER.ino

* Update 4A9A1-THROTTLE_CONTROLLER.ino

* Update 4A9A1-THROTTLE_CONTROLLER.ino

* testing adding the Arduino library as a submodule

Trying to fix the CI compile issue with for the SPI.h include on SimpleFOC.

* Update Makefile

* Revert "testing adding the Arduino library as a submodule"

This reverts commit a83a43c82e058004b11b79e433b8496bcd63c0f0.

* Revert "Update Makefile"

This reverts commit 819c123939ccb40010576183f127d6d7abc612cf.

* Delete .gitmodules

* Adding the SPI.h files directly to the throttle folder for SimpleFOC

* Revert "Delete .gitmodules"

This reverts commit cb70eba16fff09f35522731a57b8b71b8a761fad.

* Revert "Adding the SPI.h files directly to the throttle folder for SimpleFOC"

This reverts commit b3bd712d716b8f9a0028f4d0bac6ae6b7ab37786.

* Fixed spelling

CI still doesn't work.

* Merge .gitmodules from develop and PR branch (restore missing submodules)

* Updated Throttle to use OH MT6835 Library

* updated git module and throttle controller

updated git modules to remove reference to simple foc, and updated throttle code accordingly for the use of OH MT6836 library, with note it's derived from simple foc (library includes the note as well, just making sure it's doubly obvious).

* update esp.mk to try removing fast LED

* reverting esp.mk and removing servo library reference from throttle mk.

* Update ci.yaml

testing only making the throttle

* Update ci.yaml

* Update ci.yaml

* Update ci.yaml

* Update 4A9A1-THROTTLE_CONTROLLER.ino

cleaned up include calls.

* Exclude FastLED examples from build process

Added $(LIBRARY_DIR)/FastLED/examples to the EXCLUDE_DIRS variable in esp.mk to prevent compilation and linking of example files from the FastLED library.

* Limit makeEspArduino library search to declared sketch libs

Use the sketch's LIBRARIES list to pass only declared repo libraries
(not the entire repo libraries directory) while letting makeEspArduino
discover ESP core libraries separately.

* Add mapHallSensor function forward declaration

To fix this error:
4A9A1-THROTTLE_CONTROLLER.ino.cpp:287:22: error: 'mapHallSensor' was not declared in this scope

* Forward declare requestEvent function

To fix this error:
4A9A1A1-THROTTLE_INNER_GRIP.ino:100:18: error: ‘requestEvent’ was not declared in this scope

* Throttle inner grip libraries only need Wire

---------

Co-authored-by: Arribe <47125808+Arribe@users.noreply.github.com>
Co-authored-by: Jianming "Ash" Chen <ashchan@gmail.com>